USE [master]
GO
/****** Object:  Database [RapidPay]    Script Date: 25/11/2021 19:16:13 ******/
CREATE DATABASE [RapidPay]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RapidPay', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RapidPay.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RapidPay_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\RapidPay_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [RapidPay] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RapidPay].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RapidPay] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RapidPay] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RapidPay] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RapidPay] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RapidPay] SET ARITHABORT OFF 
GO
ALTER DATABASE [RapidPay] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RapidPay] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RapidPay] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RapidPay] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RapidPay] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RapidPay] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RapidPay] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RapidPay] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RapidPay] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RapidPay] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RapidPay] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RapidPay] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RapidPay] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RapidPay] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RapidPay] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RapidPay] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RapidPay] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RapidPay] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RapidPay] SET  MULTI_USER 
GO
ALTER DATABASE [RapidPay] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RapidPay] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RapidPay] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RapidPay] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RapidPay] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RapidPay] SET QUERY_STORE = OFF
GO
USE [RapidPay]
GO
/****** Object:  User [usr_RapidPay]    Script Date: 25/11/2021 19:16:14 ******/
CREATE USER [usr_RapidPay] FOR LOGIN [usr_RapidPay] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [usr_RapidPay]
GO
/****** Object:  Table [dbo].[Card]    Script Date: 25/11/2021 19:16:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Card](
	[CardId] [int] IDENTITY(1,1) NOT NULL,
	[Number] [char](15) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Balance] [decimal](10, 2) NOT NULL,
 CONSTRAINT [PK_Card] PRIMARY KEY CLUSTERED 
(
	[CardId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Payment]    Script Date: 25/11/2021 19:16:14 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Payment](
	[PaymentId] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [decimal](10, 2) NOT NULL,
	[Fee] [decimal](10, 2) NOT NULL,
	[TotalAmount] [decimal](10, 2) NOT NULL,
	[CardId] [int] NOT NULL,
 CONSTRAINT [PK_Payment] PRIMARY KEY CLUSTERED 
(
	[PaymentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Card_Number]    Script Date: 25/11/2021 19:16:14 ******/
CREATE NONCLUSTERED INDEX [IX_Card_Number] ON [dbo].[Card]
(
	[Number] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Payment]  WITH CHECK ADD  CONSTRAINT [FK_Payment_Card] FOREIGN KEY([CardId])
REFERENCES [dbo].[Card] ([CardId])
GO
ALTER TABLE [dbo].[Payment] CHECK CONSTRAINT [FK_Payment_Card]
GO
USE [master]
GO
ALTER DATABASE [RapidPay] SET  READ_WRITE 
GO
